
/**************************************************************
 *	
 *	cheerup, 8 bit, 11025Hz,
 *	1 channel, 2249917 bytes/channel
 *	Total Size: 1 * 2249917 + 4 (header) = 2249961 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/cheerup.wav
 *	Time-stamp: Sun Nov 26 00:27:25 2017
 *	
 **************************************************************/

#ifndef __CHEERUPH__
#define __CHEERUPH__

#define CHEERUPFREQ 11025
#define CHEERUPLEN 2249917

extern const unsigned char cheerup[2249917];

#endif /* __CHEERUPH__ */
