
/**************************************************************
 *	
 *	knocknock, 8 bit, 11025Hz,
 *	1 channel, 2170025 bytes/channel
 *	Total Size: 1 * 2170025 + 4 (header) = 2170069 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/knocknock.wav
 *	Time-stamp: Sun Nov 26 00:13:39 2017
 *	
 **************************************************************/

#ifndef __KNOCKNOCKH__
#define __KNOCKNOCKH__

#define KNOCKNOCKFREQ 11025
#define KNOCKNOCKLEN 2170025

extern const unsigned char knocknock[2170025];

#endif /* __KNOCKNOCKH__ */
