
/**************************************************************
 *	
 *	likey, 8 bit, 11025Hz,
 *	1 channel, 2294088 bytes/channel
 *	Total Size: 1 * 2294088 + 4 (header) = 2294132 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/likey.wav
 *	Time-stamp: Sat Nov 25 23:35:16 2017
 *	
 **************************************************************/

#ifndef __LIKEYH__
#define __LIKEYH__

#define LIKEYFREQ 11025
#define LIKEYLEN 2294088

extern const unsigned char likey[2294088];

#endif /* __LIKEYH__ */
