
/**************************************************************
 *	
 *	pauseaudio, 8 bit, 11025Hz,
 *	1 channel, 2182590 bytes/channel
 *	Total Size: 1 * 2182590 + 4 (header) = 2182634 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/pauseaudio.wav
 *	Time-stamp: Sat Nov 25 22:42:12 2017
 *	
 **************************************************************/

#ifndef __PAUSEAUDIOH__
#define __PAUSEAUDIOH__

#define PAUSEAUDIOFREQ 11025
#define PAUSEAUDIOLEN 2182590

extern const unsigned char pauseaudio[2182590];

#endif /* __PAUSEAUDIOH__ */
