
/**************************************************************
 *	
 *	poof, 8 bit, 11025Hz,
 *	1 channel, 5103 bytes/channel
 *	Total Size: 1 * 5103 + 4 (header) = 5147 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/poof.wav
 *	Time-stamp: Sun Nov 26 00:41:35 2017
 *	
 **************************************************************/

#ifndef __POOFH__
#define __POOFH__

#define POOFFREQ 11025
#define POOFLEN 5103

extern const unsigned char poof[5103];

#endif /* __POOFH__ */
