
/**************************************************************
 *	
 *	POWER_EXO_8_bits, 8 bit, 11025Hz,
 *	1 channel, 2454604 bytes/channel
 *	Total Size: 1 * 2454604 + 4 (header) = 2454648 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/POWER-EXO-8-bits.wav
 *	Time-stamp: Sat Nov 25 22:57:42 2017
 *	
 **************************************************************/

#ifndef __POWER_EXO_8_BITSH__
#define __POWER_EXO_8_BITSH__

#define POWER_EXO_8_BITSFREQ 11025
#define POWER_EXO_8_BITSLEN 2454604

extern const unsigned char POWER_EXO_8_bits[2454604];

#endif /* __POWER_EXO_8_BITSH__ */
