
/**************************************************************
 *	
 *	startaudio, 8 bit, 11025Hz,
 *	1 channel, 2294088 bytes/channel
 *	Total Size: 1 * 2294088 + 4 (header) = 2294132 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/startaudio.wav
 *	Time-stamp: Sat Nov 25 23:02:48 2017
 *	
 **************************************************************/

#ifndef __STARTAUDIOH__
#define __STARTAUDIOH__

#define STARTAUDIOFREQ 11025
#define STARTAUDIOLEN 2294088

extern const unsigned char startaudio[2294088];

#endif /* __STARTAUDIOH__ */
