
/**************************************************************
 *	
 *	tt, 8 bit, 11025Hz,
 *	1 channel, 2311783 bytes/channel
 *	Total Size: 1 * 2311783 + 4 (header) = 2311827 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Chris/Documents/CS 2261/finalproject/m02/music/tt.wav
 *	Time-stamp: Sun Nov 26 00:27:20 2017
 *	
 **************************************************************/

#ifndef __TTH__
#define __TTH__

#define TTFREQ 11025
#define TTLEN 2311783

extern const unsigned char tt[2311783];

#endif /* __TTH__ */
